  alias: Reset toggle switch
  trigger:
  - entity_id: binary_sensor.toggle_switch
    for: 00:00:01
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      payload: 0A8796off
      topic: tele/sonoff/RESULT
    service: mqtt.publish
- id: '1570374809523'
  alias: toggle input boolean
  trigger:
  - entity_id: binary_sensor.toggle_switch
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: input_boolean.toggle
    service: input_boolean.toggle
