
binary_sensor:
  - platform: mqtt
    state_topic: "tele/sonoff/RESULT"
    name: 'toggle switch'
    value_template: '{{value_json.RfReceived.Data}}'
    payload_on: '0A8796'
    payload_off: '0A8796off'
input_boolean:
  toggle:
    name: toggle switch
    initial: off

